services:
  oracle-23.9.0.0:
    image: container-registry.oracle.com/database/free:23.9.0.0
    container_name: "23.9.0.0"
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=MySecurePass
